/* GERADO por ferramentas/gerar-megas.ps1 a partir da PokeAPI - nao editar a mao (rode o script de novo).
   Formas de Mega Evolucao e de Reversao Primitiva, por especie (89 especies, 96 formas).
   Charizard e Mewtwo tem duas (X e Y): por isso o valor e sempre uma LISTA.
   So o indice mora aqui; status, tipos, habilidade e sprite da forma vem da API pelo nome (orma), como
   qualquer outro Pokemon - e sao pre-carregados no comeco da batalha pra nao esperar rede no meio do turno. */
export const MEGAS = {
  'venusaur': [{ forma: 'venusaur-mega', id: 10033, nome: 'Mega Venusaur' }],
  'charizard': [{ forma: 'charizard-mega-x', id: 10034, nome: 'Mega Charizard X' }, { forma: 'charizard-mega-y', id: 10035, nome: 'Mega Charizard Y' }],
  'blastoise': [{ forma: 'blastoise-mega', id: 10036, nome: 'Mega Blastoise' }],
  'alakazam': [{ forma: 'alakazam-mega', id: 10037, nome: 'Mega Alakazam' }],
  'gengar': [{ forma: 'gengar-mega', id: 10038, nome: 'Mega Gengar' }],
  'kangaskhan': [{ forma: 'kangaskhan-mega', id: 10039, nome: 'Mega Kangaskhan' }],
  'pinsir': [{ forma: 'pinsir-mega', id: 10040, nome: 'Mega Pinsir' }],
  'gyarados': [{ forma: 'gyarados-mega', id: 10041, nome: 'Mega Gyarados' }],
  'aerodactyl': [{ forma: 'aerodactyl-mega', id: 10042, nome: 'Mega Aerodactyl' }],
  'mewtwo': [{ forma: 'mewtwo-mega-x', id: 10043, nome: 'Mega Mewtwo X' }, { forma: 'mewtwo-mega-y', id: 10044, nome: 'Mega Mewtwo Y' }],
  'ampharos': [{ forma: 'ampharos-mega', id: 10045, nome: 'Mega Ampharos' }],
  'scizor': [{ forma: 'scizor-mega', id: 10046, nome: 'Mega Scizor' }],
  'heracross': [{ forma: 'heracross-mega', id: 10047, nome: 'Mega Heracross' }],
  'houndoom': [{ forma: 'houndoom-mega', id: 10048, nome: 'Mega Houndoom' }],
  'tyranitar': [{ forma: 'tyranitar-mega', id: 10049, nome: 'Mega Tyranitar' }],
  'blaziken': [{ forma: 'blaziken-mega', id: 10050, nome: 'Mega Blaziken' }],
  'gardevoir': [{ forma: 'gardevoir-mega', id: 10051, nome: 'Mega Gardevoir' }],
  'mawile': [{ forma: 'mawile-mega', id: 10052, nome: 'Mega Mawile' }],
  'aggron': [{ forma: 'aggron-mega', id: 10053, nome: 'Mega Aggron' }],
  'medicham': [{ forma: 'medicham-mega', id: 10054, nome: 'Mega Medicham' }],
  'manectric': [{ forma: 'manectric-mega', id: 10055, nome: 'Mega Manectric' }],
  'banette': [{ forma: 'banette-mega', id: 10056, nome: 'Mega Banette' }],
  'absol': [{ forma: 'absol-mega', id: 10057, nome: 'Mega Absol' }],
  'garchomp': [{ forma: 'garchomp-mega', id: 10058, nome: 'Mega Garchomp' }],
  'lucario': [{ forma: 'lucario-mega', id: 10059, nome: 'Mega Lucario' }],
  'abomasnow': [{ forma: 'abomasnow-mega', id: 10060, nome: 'Mega Abomasnow' }],
  'latias': [{ forma: 'latias-mega', id: 10062, nome: 'Mega Latias' }],
  'latios': [{ forma: 'latios-mega', id: 10063, nome: 'Mega Latios' }],
  'swampert': [{ forma: 'swampert-mega', id: 10064, nome: 'Mega Swampert' }],
  'sceptile': [{ forma: 'sceptile-mega', id: 10065, nome: 'Mega Sceptile' }],
  'sableye': [{ forma: 'sableye-mega', id: 10066, nome: 'Mega Sableye' }],
  'altaria': [{ forma: 'altaria-mega', id: 10067, nome: 'Mega Altaria' }],
  'gallade': [{ forma: 'gallade-mega', id: 10068, nome: 'Mega Gallade' }],
  'audino': [{ forma: 'audino-mega', id: 10069, nome: 'Mega Audino' }],
  'sharpedo': [{ forma: 'sharpedo-mega', id: 10070, nome: 'Mega Sharpedo' }],
  'slowbro': [{ forma: 'slowbro-mega', id: 10071, nome: 'Mega Slowbro' }],
  'steelix': [{ forma: 'steelix-mega', id: 10072, nome: 'Mega Steelix' }],
  'pidgeot': [{ forma: 'pidgeot-mega', id: 10073, nome: 'Mega Pidgeot' }],
  'glalie': [{ forma: 'glalie-mega', id: 10074, nome: 'Mega Glalie' }],
  'diancie': [{ forma: 'diancie-mega', id: 10075, nome: 'Mega Diancie' }],
  'metagross': [{ forma: 'metagross-mega', id: 10076, nome: 'Mega Metagross' }],
  'kyogre': [{ forma: 'kyogre-primal', id: 10077, nome: 'Kyogre Primitivo', primal: true }],
  'groudon': [{ forma: 'groudon-primal', id: 10078, nome: 'Groudon Primitivo', primal: true }],
  'rayquaza': [{ forma: 'rayquaza-mega', id: 10079, nome: 'Mega Rayquaza' }],
  'camerupt': [{ forma: 'camerupt-mega', id: 10087, nome: 'Mega Camerupt' }],
  'lopunny': [{ forma: 'lopunny-mega', id: 10088, nome: 'Mega Lopunny' }],
  'salamence': [{ forma: 'salamence-mega', id: 10089, nome: 'Mega Salamence' }],
  'beedrill': [{ forma: 'beedrill-mega', id: 10090, nome: 'Mega Beedrill' }],
  'clefable': [{ forma: 'clefable-mega', id: 10278, nome: 'Mega Clefable' }],
  'victreebel': [{ forma: 'victreebel-mega', id: 10279, nome: 'Mega Victreebel' }],
  'starmie': [{ forma: 'starmie-mega', id: 10280, nome: 'Mega Starmie' }],
  'dragonite': [{ forma: 'dragonite-mega', id: 10281, nome: 'Mega Dragonite' }],
  'meganium': [{ forma: 'meganium-mega', id: 10282, nome: 'Mega Meganium' }],
  'feraligatr': [{ forma: 'feraligatr-mega', id: 10283, nome: 'Mega Feraligatr' }],
  'skarmory': [{ forma: 'skarmory-mega', id: 10284, nome: 'Mega Skarmory' }],
  'froslass': [{ forma: 'froslass-mega', id: 10285, nome: 'Mega Froslass' }],
  'emboar': [{ forma: 'emboar-mega', id: 10286, nome: 'Mega Emboar' }],
  'excadrill': [{ forma: 'excadrill-mega', id: 10287, nome: 'Mega Excadrill' }],
  'scolipede': [{ forma: 'scolipede-mega', id: 10288, nome: 'Mega Scolipede' }],
  'scrafty': [{ forma: 'scrafty-mega', id: 10289, nome: 'Mega Scrafty' }],
  'eelektross': [{ forma: 'eelektross-mega', id: 10290, nome: 'Mega Eelektross' }],
  'chandelure': [{ forma: 'chandelure-mega', id: 10291, nome: 'Mega Chandelure' }],
  'chesnaught': [{ forma: 'chesnaught-mega', id: 10292, nome: 'Mega Chesnaught' }],
  'delphox': [{ forma: 'delphox-mega', id: 10293, nome: 'Mega Delphox' }],
  'greninja': [{ forma: 'greninja-mega', id: 10294, nome: 'Mega Greninja' }],
  'pyroar': [{ forma: 'pyroar-mega', id: 10295, nome: 'Mega Pyroar' }],
  'floette': [{ forma: 'floette-mega', id: 10296, nome: 'Mega Floette' }],
  'malamar': [{ forma: 'malamar-mega', id: 10297, nome: 'Mega Malamar' }],
  'barbaracle': [{ forma: 'barbaracle-mega', id: 10298, nome: 'Mega Barbaracle' }],
  'dragalge': [{ forma: 'dragalge-mega', id: 10299, nome: 'Mega Dragalge' }],
  'hawlucha': [{ forma: 'hawlucha-mega', id: 10300, nome: 'Mega Hawlucha' }],
  'zygarde': [{ forma: 'zygarde-mega', id: 10301, nome: 'Mega Zygarde' }],
  'drampa': [{ forma: 'drampa-mega', id: 10302, nome: 'Mega Drampa' }],
  'falinks': [{ forma: 'falinks-mega', id: 10303, nome: 'Mega Falinks' }],
  'raichu': [{ forma: 'raichu-mega-x', id: 10304, nome: 'Mega Raichu X' }, { forma: 'raichu-mega-y', id: 10305, nome: 'Mega Raichu Y' }],
  'chimecho': [{ forma: 'chimecho-mega', id: 10306, nome: 'Mega Chimecho' }],
  'staraptor': [{ forma: 'staraptor-mega', id: 10308, nome: 'Mega Staraptor' }],
  'heatran': [{ forma: 'heatran-mega', id: 10311, nome: 'Mega Heatran' }],
  'darkrai': [{ forma: 'darkrai-mega', id: 10312, nome: 'Mega Darkrai' }],
  'golurk': [{ forma: 'golurk-mega', id: 10313, nome: 'Mega Golurk' }],
  'meowstic': [{ forma: 'meowstic-male-mega', id: 10314, nome: 'Mega Meowstic' }],
  'crabominable': [{ forma: 'crabominable-mega', id: 10315, nome: 'Mega Crabominable' }],
  'golisopod': [{ forma: 'golisopod-mega', id: 10316, nome: 'Mega Golisopod' }],
  'magearna': [{ forma: 'magearna-mega', id: 10317, nome: 'Mega Magearna' }],
  'zeraora': [{ forma: 'zeraora-mega', id: 10319, nome: 'Mega Zeraora' }],
  'scovillain': [{ forma: 'scovillain-mega', id: 10320, nome: 'Mega Scovillain' }],
  'glimmora': [{ forma: 'glimmora-mega', id: 10321, nome: 'Mega Glimmora' }],
  'tatsugiri': [{ forma: 'tatsugiri-curly-mega', id: 10322, nome: 'Mega Tatsugiri' }],
  'baxcalibur': [{ forma: 'baxcalibur-mega', id: 10325, nome: 'Mega Baxcalibur' }]
};
export const megasDe = especie => MEGAS[especie] || [];
export const temMega = especie => !!MEGAS[especie];
// Groudon e Kyogre nao "megaevoluem": o nome da mecanica deles e Reversao Primitiva (mesma mecanica, outro nome)
export const ehPrimal = forma => !!forma?.primal;