/* GERADO pelo editor de rotas do jogo (js/tela-editor-rotas.js → "📋 Copiar o arquivo") — não editar à mão.
   Semeado em 2026-10-01 por ferramentas/semear-rotas.mjs.

   Duas coisas moram aqui, e as duas são AJUSTES por cima de js/dados-mapas.js (que é gerado da PokéAPI e não deve
   guardar escolha de desenho):
     ALFAS        → troca o Alfa de uma rota ({ id, nome, nivel }). Rota fora da tabela = o Alfa do mapa.
     MISSOES_ROTA → as missões de espécie e de Alfa de cada rota, uma por rota.
   Quem aplica os dois é js/dados.js (o ÚNICO que importa dados-mapas.js). Sem imports aqui de propósito: é dado,
   e precisa ser legível e carregável sem depender de nada. */

/* Uma missão de espécie. `alvos` = [[espécie, quantidade]…]: mais de uma espécie SOMA (8 Plusle + 8 Minun = 16).
   `libera` com `qualquer: 1` = basta derrotar UM de qualquer uma delas pra missão aparecer. */
const esp = (gen, rota, nome, alvos, premio) => ({
  id: `${rota}-esp`, gen, rota, nome, premio,
  desc: `Derrote ${alvos.map(([n, q]) => `${q} ${bonito(n)}`).join(' e ')}.`,
  libera: { alvos: alvos.map(([n]) => [n, 1]), qualquer: 1 },
  objetivo: { alvos }
});
/* A missão do Alfa da rota. `antes` = id da rota anterior (a corrente do mapa); null na primeira, que libera no
   nível 1. `lendarios` marca a rota final: lá o "Alfa" são os lendários, e vencer fecha a Gen. */
const alfa = (gen, rota, nome, rotulo, antes, premio, lendarios) => ({
  id: `${rota}-alfa`, gen, rota, nome, premio,
  desc: lendarios ? `Vença os lendários de ${rotulo} e feche a Gen ${gen}.` : `Derrote o Alfa de ${rotulo}.`,
  libera: antes ? { chefe: antes } : { nivel: 1 },
  objetivo: { chefe: rota }
});
// "nidoran-f" → "Nidoran F", "mr-mime" → "Mr Mime": o nome da espécie como o jogador lê na descrição
const bonito = n => n.split('-').map(p => p[0].toUpperCase() + p.slice(1)).join(' ');

// Alfa trocado por rota. Vazio = todos os mapas seguem com o Alfa que a PokéAPI gerou.
export const ALFAS = {};

export const MISSOES_ROTA = [
  // ---- Gen 1: Kanto ----
  esp(1, "rota1", "Praga de Rattata", [["rattata",24]], {"itens":{"potion":4}}),
  alfa(1, "rota1", "O Alfa da Rota 1", "Rota 1", null, {"dinheiro":1000}, false),
  esp(1, "floresta", "Folhas mastigadas", [["caterpie",24]], {"itens":{"honey":2}}),
  alfa(1, "floresta", "Rainha da Floresta", "Floresta de Viridian", "rota1", {"dinheiro":2000}, false),
  esp(1, "montelua", "Quebra-pedra", [["geodude",24]], {"itens":{"hard-stone":2}}),
  alfa(1, "montelua", "A lua cheia", "Monte Lua", "floresta", {"dinheiro":3000}, false),
  esp(1, "rota24", "Pinças na Ponte Pepita", [["krabby",24]], {"itens":{"super-potion":2}}),
  alfa(1, "rota24", "Punho da Rota 24", "Rota 24", "montelua", {"dinheiro":4000}, false),
  esp(1, "k-usina", "Bombas rolando", [["voltorb",16]], {"itens":{"rare-candy":1}}),
  alfa(1, "k-usina", "Curto-circuito", "Usina Elétrica", "rota24", {"dinheiro":5000}, false),
  esp(1, "torre", "Caça-fantasmas", [["haunter",12]], {"itens":{"revive":1}}),
  alfa(1, "torre", "A sombra da Torre", "Torre Pokémon", "k-usina", {"dinheiro":6000}, false),
  esp(1, "safari", "Rei e rainha do Safari", [["nidoking",4],["nidoqueen",4]], {"itens":{"hyper-potion":2}}),
  alfa(1, "safari", "Estouro no Safari", "Zona Safari", "torre", {"dinheiro":7000}, false),
  esp(1, "k-ilhas", "Cascos de fogo no gelo", [["ponyta",16]], {"itens":{"rare-candy":2}}),
  alfa(1, "k-ilhas", "Serpente do mar", "Ilhas Espuma", "safari", {"dinheiro":8000}, false),
  esp(1, "k-vitoria", "Quatro braços, uma estrada", [["machamp",8]], {"itens":{"max-revive":1}}),
  alfa(1, "k-vitoria", "O último portão", "Estrada Vitória", "k-ilhas", {"dinheiro":9000}, false),
  esp(1, "caverna", "Lâminas no escuro", [["scyther",8]], {"dinheiro":12000}),
  alfa(1, "caverna", "Campeão de Kanto", "Caverna Cerúlea", "k-vitoria", {"dinheiro":25000,"itens":{"rare-candy":3}}, true),
  // ---- Gen 2: Johto ----
  esp(2, "j-rota29", "Rabos na trilha", [["sentret",24]], {"itens":{"potion":4}}),
  alfa(2, "j-rota29", "O Alfa da Rota 29", "Rota 29", null, {"dinheiro":1000}, false),
  esp(2, "j-ilex", "Lã no bosque", [["mareep",24]], {"itens":{"honey":2}}),
  alfa(2, "j-ilex", "Girassol do Ilex", "Bosque Ilex", "j-rota29", {"dinheiro":2000}, false),
  esp(2, "j-ruinas", "Alfabeto quebrado", [["unown",24]], {"itens":{"hard-stone":2}}),
  alfa(2, "j-ruinas", "Presas nas ruínas", "Ruínas de Alph", "j-ilex", {"dinheiro":3000}, false),
  esp(2, "j-olivine", "Luzes no fundo", [["chinchou",16]], {"itens":{"super-potion":2}}),
  alfa(2, "j-olivine", "Farol vivo", "Costa de Olivine", "j-ruinas", {"dinheiro":4000}, false),
  esp(2, "j-queimada", "Fogo que não apagou", [["houndour",12]], {"itens":{"rare-candy":1}}),
  alfa(2, "j-queimada", "Urso das cinzas", "Torre Queimada", "j-olivine", {"dinheiro":5000}, false),
  esp(2, "j-furia", "Lã elétrica", [["ampharos",8]], {"itens":{"revive":1}}),
  alfa(2, "j-furia", "Asas no lago", "Lago da Fúria", "j-queimada", {"dinheiro":6000}, false),
  esp(2, "j-gelo", "Nunca é só um", [["dunsparce",16]], {"itens":{"hyper-potion":2}}),
  alfa(2, "j-gelo", "Coral do gelo", "Caminho de Gelo", "j-furia", {"dinheiro":7000}, false),
  esp(2, "j-dragao", "Espinhos na água", [["qwilfish",8]], {"itens":{"rare-candy":2}}),
  alfa(2, "j-dragao", "Guardião da toca", "Toca do Dragão", "j-gelo", {"dinheiro":8000}, false),
  esp(2, "j-prata", "Casca dura", [["shuckle",16]], {"itens":{"max-revive":1}}),
  alfa(2, "j-prata", "O topo do Monte Prata", "Monte Prata", "j-dragao", {"dinheiro":9000}, false),
  esp(2, "j-sino", "Leite da montanha", [["miltank",8]], {"dinheiro":12000}),
  alfa(2, "j-sino", "Campeão de Johto", "Torre do Sino", "j-prata", {"dinheiro":25000,"itens":{"rare-candy":3}}, true),
  // ---- Gen 3: Hoenn ----
  esp(3, "h-rota101", "Zigue e zague", [["zigzagoon",24]], {"itens":{"potion":4}}),
  alfa(3, "h-rota101", "O Alfa da Rota 101", "Rota 101", null, {"dinheiro":1000}, false),
  esp(3, "h-petalburgo", "Folha sobre a água", [["lotad",12],["seedot",12]], {"itens":{"honey":2}}),
  alfa(3, "h-petalburgo", "Asas de pó", "Bosque Petalburgo", "h-rota101", {"dinheiro":2000}, false),
  esp(3, "h-granito", "Barriga de lama", [["gulpin",24]], {"itens":{"hard-stone":2}}),
  alfa(3, "h-granito", "Palma aberta", "Caverna Granito", "h-petalburgo", {"dinheiro":3000}, false),
  esp(3, "h-rota110", "Dentes na ciclovia", [["carvanha",24]], {"itens":{"super-potion":2}}),
  alfa(3, "h-rota110", "Beleza das águas", "Rota 110", "h-granito", {"dinheiro":4000}, false),
  esp(3, "h-chimney", "Dança sem motivo", [["spinda",24]], {"itens":{"rare-candy":1}}),
  alfa(3, "h-chimney", "Engolindo tudo", "Monte Chimney", "h-rota110", {"dinheiro":5000}, false),
  esp(3, "h-deserto", "Bússola quebrada", [["nosepass",24]], {"itens":{"revive":1}}),
  alfa(3, "h-deserto", "Fóssil de armadura", "Deserto da Rota 111", "h-chimney", {"dinheiro":6000}, false),
  esp(3, "h-pira", "Mais ou Menos", [["plusle",8],["minun",8]], {"itens":{"hyper-potion":2}}),
  alfa(3, "h-pira", "Punho de aço", "Monte Pira", "h-deserto", {"dinheiro":7000}, false),
  esp(3, "h-mar", "Língua camaleão", [["kecleon",16]], {"itens":{"rare-candy":2}}),
  alfa(3, "h-mar", "Gelo flutuante", "Mar de Hoenn", "h-pira", {"dinheiro":8000}, false),
  esp(3, "h-shoal", "Carvão vivo", [["torkoal",12]], {"itens":{"max-revive":1}}),
  alfa(3, "h-shoal", "Asas de dragão", "Caverna Shoal", "h-mar", {"dinheiro":9000}, false),
  esp(3, "h-pilar", "Palmeira voadora", [["tropius",16]], {"dinheiro":12000}),
  alfa(3, "h-pilar", "Campeão de Hoenn", "Pilar Celeste", "h-shoal", {"dinheiro":25000,"itens":{"rare-candy":3}}, true),
  // ---- Gen 4: Sinnoh ----
  esp(4, "s-rota201", "Dentes de castor", [["bidoof",24]], {"itens":{"potion":4}}),
  alfa(4, "s-rota201", "O Alfa da Rota 201", "Rota 201", null, {"dinheiro":1000}, false),
  esp(4, "s-eterna", "Botão fechado", [["budew",24]], {"itens":{"honey":2}}),
  alfa(4, "s-eterna", "A capa do bosque", "Bosque Eterna", "s-rota201", {"dinheiro":2000}, false),
  esp(4, "s-oreburgh", "Sino de bronze", [["bronzor",24]], {"itens":{"hard-stone":2}}),
  alfa(4, "s-oreburgh", "Garras na mina", "Mina Oreburgh", "s-eterna", {"dinheiro":3000}, false),
  esp(4, "s-eolico", "Nadadeira veloz", [["buizel",16]], {"itens":{"super-potion":2}}),
  alfa(4, "s-eolico", "Juba elétrica", "Vale Eólico", "s-oreburgh", {"dinheiro":4000}, false),
  esp(4, "s-pantano", "Cheiro de longe", [["stunky",24]], {"itens":{"rare-candy":1}}),
  alfa(4, "s-pantano", "Boca de areia", "Grande Pântano", "s-eolico", {"dinheiro":5000}, false),
  esp(4, "s-mansao", "Sinos na mansão", [["bronzong",12]], {"itens":{"revive":1}}),
  alfa(4, "s-mansao", "Campana dupla", "Mansão Velha", "s-pantano", {"dinheiro":6000}, false),
  esp(4, "s-neve", "Esquilo de choque", [["pachirisu",16]], {"itens":{"hyper-potion":2}}),
  alfa(4, "s-neve", "Raposa de gelo", "Rota 216", "s-mansao", {"dinheiro":7000}, false),
  esp(4, "s-vitoria", "Escudo fóssil", [["bastiodon",8]], {"itens":{"rare-candy":2}}),
  alfa(4, "s-vitoria", "Ímã triplo", "Estrada Vitória", "s-neve", {"dinheiro":8000}, false),
  esp(4, "s-sobrevivencia", "Planta carnívora", [["carnivine",16]], {"itens":{"max-revive":1}}),
  alfa(4, "s-sobrevivencia", "Dragão da terra", "Área de Sobrevivência", "s-vitoria", {"dinheiro":9000}, false),
  esp(4, "s-lanca", "Bruxa do pilar", [["mismagius",8]], {"dinheiro":12000}),
  alfa(4, "s-lanca", "Campeão de Sinnoh", "Pilar Lança", "s-sobrevivencia", {"dinheiro":25000,"itens":{"rare-candy":3}}, true),
  // ---- Gen 5: Unova ----
  esp(5, "u-rota1", "Sempre de guarda", [["patrat",24]], {"itens":{"potion":4}}),
  alfa(5, "u-rota1", "O Alfa da Rota 1", "Rota 1 de Unova", null, {"dinheiro":1000}, false),
  esp(5, "u-sonhos", "Pedra que anda", [["roggenrola",24]], {"itens":{"honey":2}}),
  alfa(5, "u-sonhos", "Algodão ao vento", "Bosque dos Sonhos", "u-rota1", {"dinheiro":2000}, false),
  esp(5, "u-pinwheel", "Girinos no charco", [["tympole",24]], {"itens":{"hard-stone":2}}),
  alfa(5, "u-pinwheel", "Vento de algodão", "Floresta Pinwheel", "u-sonhos", {"dinheiro":3000}, false),
  esp(5, "u-deserto", "Olhos no deserto", [["elgyem",24]], {"itens":{"super-potion":2}}),
  alfa(5, "u-deserto", "Broca na areia", "Resort Deserto", "u-pinwheel", {"dinheiro":4000}, false),
  esp(5, "u-chargestone", "Olho que não dorme", [["watchog",24]], {"itens":{"rare-candy":1}}),
  alfa(5, "u-chargestone", "Zebra elétrica", "Caverna Chargestone", "u-deserto", {"dinheiro":5000}, false),
  esp(5, "u-celestial", "Filhotes de rapina", [["rufflet",8],["vullaby",8]], {"itens":{"revive":1}}),
  alfa(5, "u-celestial", "Olhar da torre", "Torre Celestial", "u-chargestone", {"dinheiro":6000}, false),
  esp(5, "u-gelada", "Sorvete duplo", [["vanillish",12]], {"itens":{"hyper-potion":2}}),
  alfa(5, "u-gelada", "Baunilha dupla", "Caverna Gelada", "u-celestial", {"dinheiro":7000}, false),
  esp(5, "u-humilau", "Médico da baía", [["audino",24]], {"itens":{"rare-candy":2}}),
  alfa(5, "u-humilau", "Fóssil alado", "Baía Humilau", "u-gelada", {"dinheiro":8000}, false),
  esp(5, "u-vitoria", "Cacto dançante", [["maractus",24]], {"itens":{"max-revive":1}}),
  alfa(5, "u-vitoria", "Três cabeças", "Estrada Vitória de Unova", "u-humilau", {"dinheiro":9000}, false),
  esp(5, "u-castelo", "Pássaro de pedra", [["sigilyph",8]], {"dinheiro":12000}),
  alfa(5, "u-castelo", "Campeão de Unova", "Castelo de N", "u-vitoria", {"dinheiro":25000,"itens":{"rare-candy":3}}, true),
  // ---- Gen 6: Kalos ----
  esp(6, "ka-rota2", "Orelhas grandes", [["bunnelby",24]], {"itens":{"potion":4}}),
  alfa(6, "ka-rota2", "O Alfa da Rota 2", "Rota 2 de Kalos", null, {"dinheiro":1000}, false),
  esp(6, "ka-santalune", "Flor com pernas", [["flabebe",24]], {"itens":{"honey":2}}),
  alfa(6, "ka-santalune", "Asas de mosaico", "Bosque Santalune", "ka-rota2", {"dinheiro":2000}, false),
  esp(6, "ka-glittering", "Espada solta", [["honedge",16]], {"itens":{"hard-stone":2}}),
  alfa(6, "ka-glittering", "Orelhas de escavadeira", "Caverna Glittering", "ka-santalune", {"dinheiro":3000}, false),
  esp(6, "ka-riviere", "Alga venenosa", [["skrelp",12],["clauncher",12]], {"itens":{"super-potion":2}}),
  alfa(6, "ka-riviere", "Chifres do prado", "Prado Rivière", "ka-glittering", {"dinheiro":4000}, false),
  esp(6, "ka-usina", "Filhote de juba", [["litleo",16]], {"itens":{"rare-candy":1}}),
  alfa(6, "ka-usina", "Rugido na usina", "Usina de Kalos", "ka-riviere", {"dinheiro":5000}, false),
  esp(6, "ka-pantano", "Duas espadas", [["doublade",12]], {"itens":{"revive":1}}),
  alfa(6, "ka-pantano", "Panda bravo", "Pântano da Rota 14", "ka-usina", {"dinheiro":6000}, false),
  esp(6, "ka-frost", "Pétalas na neve", [["florges",8]], {"itens":{"hyper-potion":2}}),
  alfa(6, "ka-frost", "Montanha de gelo", "Gruta Frost", "ka-pantano", {"dinheiro":7000}, false),
  esp(6, "ka-azure", "Bigode elétrico", [["dedenne",16]], {"itens":{"rare-candy":2}}),
  alfa(6, "ka-azure", "Asas de som", "Costa Azure", "ka-frost", {"dinheiro":8000}, false),
  esp(6, "ka-terminus", "Corte de pelo", [["furfrou",16]], {"itens":{"max-revive":1}}),
  alfa(6, "ka-terminus", "Gosma suprema", "Caverna Terminus", "ka-azure", {"dinheiro":9000}, false),
  esp(6, "ka-arma", "Luta com capa", [["hawlucha",12]], {"dinheiro":12000}),
  alfa(6, "ka-arma", "Campeão de Kalos", "Arma Suprema", "ka-terminus", {"dinheiro":25000,"itens":{"rare-candy":3}}, true),
  // ---- Gen 7: Alola ----
  esp(7, "a-rota1", "Bico de pica-pau", [["pikipek",24]], {"itens":{"potion":4}}),
  alfa(7, "a-rota1", "O Alfa da Rota 1", "Rota 1 de Alola", null, {"dinheiro":1000}, false),
  esp(7, "a-selva", "Larva da selva", [["grubbin",24]], {"itens":{"honey":2}}),
  alfa(7, "a-selva", "Bateria viva", "Selva Lush", "a-rota1", {"dinheiro":2000}, false),
  esp(7, "a-diglett", "Cão do túnel", [["rockruff",16]], {"itens":{"hard-stone":2}}),
  alfa(7, "a-diglett", "Lobo da rocha", "Túnel Diglett", "a-selva", {"dinheiro":3000}, false),
  esp(7, "a-hano", "Caranguejo brigão", [["crabrawler",24]], {"itens":{"super-potion":2}}),
  alfa(7, "a-hano", "Bolha de água", "Praia Hano", "a-diglett", {"dinheiro":4000}, false),
  esp(7, "a-wela", "Ursinho de pelúcia", [["stufful",16]], {"itens":{"rare-candy":1}}),
  alfa(7, "a-wela", "Casco explosivo", "Parque Vulcânico Wela", "a-hano", {"dinheiro":5000}, false),
  esp(7, "a-memorial", "Burro de barro", [["mudbray",16]], {"itens":{"revive":1}}),
  alfa(7, "a-memorial", "Veneno dançante", "Morro Memorial", "a-wela", {"dinheiro":6000}, false),
  esp(7, "a-lanakila", "Besouro de choque", [["vikavolt",8]], {"itens":{"hyper-potion":2}}),
  alfa(7, "a-lanakila", "Caranguejo do topo", "Monte Lanakila", "a-memorial", {"dinheiro":7000}, false),
  esp(7, "a-poni", "Ouriço elétrico", [["togedemaru",16]], {"itens":{"rare-candy":2}}),
  alfa(7, "a-poni", "Agulha venenosa", "Cânion Vast Poni", "a-lanakila", {"dinheiro":8000}, false),
  esp(7, "a-ruinas", "Dentes afiados", [["bruxish",12]], {"itens":{"max-revive":1}}),
  alfa(7, "a-ruinas", "Escamas de batalha", "Ruínas da Abundância", "a-poni", {"dinheiro":9000}, false),
  esp(7, "a-altar", "Sábios da ilha", [["oranguru",4],["passimian",4]], {"dinheiro":12000}),
  alfa(7, "a-altar", "Campeão de Alola", "Altar do Sol e da Lua", "a-ruinas", {"dinheiro":25000,"itens":{"rare-candy":3}}, true),
  // ---- Gen 8: Galar ----
  esp(8, "g-rota1", "Bochechas cheias", [["skwovet",24]], {"itens":{"potion":4}}),
  alfa(8, "g-rota1", "O Alfa da Rota 1", "Rota 1 de Galar", null, {"dinheiro":1000}, false),
  esp(8, "g-slumbering", "Maçã com bicho", [["applin",24]], {"itens":{"honey":2}}),
  alfa(8, "g-slumbering", "Creme perfeito", "Bosque Slumbering", "g-rota1", {"dinheiro":2000}, false),
  esp(8, "g-mina", "Cobra de areia", [["silicobra",24]], {"itens":{"hard-stone":2}}),
  alfa(8, "g-mina", "Mandíbula de pedra", "Mina de Galar", "g-slumbering", {"dinheiro":3000}, false),
  esp(8, "g-miloc", "Raposa ladra", [["thievul",12]], {"itens":{"super-potion":2}}),
  alfa(8, "g-miloc", "Cão veloz", "Lago Miloc", "g-mina", {"dinheiro":4000}, false),
  esp(8, "g-motostoke", "Lã da cidade", [["dubwool",12]], {"itens":{"rare-candy":1}}),
  alfa(8, "g-motostoke", "Montanha de carvão", "Arredores de Motostoke", "g-miloc", {"dinheiro":5000}, false),
  esp(8, "g-glimwood", "Chapéu do bosque", [["hattrem",12]], {"itens":{"revive":1}}),
  alfa(8, "g-glimwood", "Bruxa do bosque", "Bosque Glimwood", "g-motostoke", {"dinheiro":6000}, false),
  esp(8, "g-rota8", "Elefante de cobre", [["copperajah",12]], {"itens":{"hyper-potion":2}}),
  alfa(8, "g-rota8", "Corvo de aço", "Rota 8 Nevada", "g-glimwood", {"dinheiro":7000}, false),
  esp(8, "g-coroa", "Duas caras, uma fome", [["morpeko",16]], {"itens":{"rare-candy":2}}),
  alfa(8, "g-coroa", "Urso da lua", "Tundra da Coroa", "g-rota8", {"dinheiro":8000}, false),
  esp(8, "g-armadura", "Pescador voador", [["cramorant",8]], {"itens":{"max-revive":1}}),
  alfa(8, "g-armadura", "Dardo de dragão", "Ilha da Armadura", "g-coroa", {"dinheiro":9000}, false),
  esp(8, "g-hammerlocke", "Cervo de outro tempo", [["wyrdeer",12]], {"dinheiro":12000}),
  alfa(8, "g-hammerlocke", "Campeão de Galar", "Torre Energia de Hammerlocke", "g-armadura", {"dinheiro":25000,"itens":{"rare-candy":3}}, true),
  // ---- Gen 9: Paldea ----
  esp(9, "p-poco", "Porquinho farejador", [["lechonk",24]], {"itens":{"potion":4}}),
  alfa(9, "p-poco", "O Alfa da Trilha de Poco", "Trilha de Poco", null, {"dinheiro":1000}, false),
  esp(9, "p-sul", "Patinha elétrica", [["pawmi",16]], {"itens":{"honey":2}}),
  alfa(9, "p-sul", "Sapo-bateria", "Planície Sul", "p-poco", {"dinheiro":2000}, false),
  esp(9, "p-caverna", "Pedra de sal", [["nacli",24]], {"itens":{"hard-stone":2}}),
  alfa(9, "p-caverna", "Gafanhoto assassino", "Caverna de Alfornada", "p-sul", {"dinheiro":3000}, false),
  esp(9, "p-casseroya", "Golfinho do lago", [["finizen",16]], {"itens":{"super-potion":2}}),
  alfa(9, "p-casseroya", "Maçã de muitas cabeças", "Lago Casseroya", "p-caverna", {"dinheiro":4000}, false),
  esp(9, "p-asado", "Cogumelo que nada", [["toedscool",16]], {"itens":{"rare-candy":1}}),
  alfa(9, "p-asado", "Cavaleiro de fogo", "Deserto Asado", "p-casseroya", {"dinheiro":5000}, false),
  esp(9, "p-tagtree", "Azeitona madura", [["dolliv",12]], {"itens":{"revive":1}}),
  alfa(9, "p-tagtree", "Chá do bosque", "Bosque Tagtree", "p-asado", {"dinheiro":6000}, false),
  esp(9, "p-glaseado", "Pássaro barulhento", [["squawkabilly",16]], {"itens":{"hyper-potion":2}}),
  alfa(9, "p-glaseado", "Baleia da montanha", "Monte Glaseado", "p-tagtree", {"dinheiro":7000}, false),
  esp(9, "p-kitakami", "Pinça lateral", [["klawf",12]], {"itens":{"rare-candy":2}}),
  alfa(9, "p-kitakami", "Fúria sem fim", "Kitakami", "p-glaseado", {"dinheiro":8000}, false),
  esp(9, "p-borda", "Peixe disfarçado", [["tatsugiri",12]], {"itens":{"max-revive":1}}),
  alfa(9, "p-borda", "Ponte de aço", "Borda da Grande Cratera", "p-kitakami", {"dinheiro":9000}, false),
  esp(9, "p-zero", "Lagarto-moto", [["cyclizar",16]], {"dinheiro":12000}),
  alfa(9, "p-zero", "Campeão de Paldea", "Área Zero", "p-borda", {"dinheiro":25000,"itens":{"rare-candy":3}}, true),
];
